SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE,
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;



SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE,
		NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
		FROM EMPLOYEE
		LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
		JOIN JOB USING(JOB_CODE)
		WHERE EMP_ID = 200;
		
	
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE,
		NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
		FROM EMPLOYEE
		LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
		JOIN JOB USING(JOB_CODE)
		WHERE DEPT_TITLE = '총무부';
		
	
	
SELECT NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
GROUP BY DEPT_TITLE;



SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE,
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE EMP_NO = '621231-1985634';


SELECT JOB_NAME, ROUND(AVG(SALARY))
		FROM EMPLOYEE
		LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
		JOIN JOB USING(JOB_CODE)
		GROUP BY JOB_CODE, JOB_NAME
		ORDER BY JOB_CODE;










