-- 1번 문제
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY "학생 이름";


-- 2번 문제
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';
ORDER BY STUDENT_SSN DESC;


-- 3번 문제
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '강원%'
OR STUDENT_ADDRESS LIKE '경기%'
ORDER BY STUDENT_NAME;


-- 4번 문제
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;


-- 5번 문제
SELECT STUDENT_NO, TO_CHAR(POINT, '9.99') POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND TERM_NO = '200402'
ORDER BY POINT DESC;


-- 6번 문제
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;


-- 7번 문제
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);


-- 8번 문제
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
RIGHT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
LEFT JOIN TB_PROFESSOR USING (PROFESSOR_NO);

--SELECT C.CLASS_NAME, PROFESSOR_NAME
--FROM TB_CLASS
--RIGHT JOIN TB_CLASS_PROFESSOR CP USING (CLASS_NO)
--LEFT JOIN TB_PROFESSOR USING (PROFESSOR_NO)
--JOIN TB_CLASS_PROFESSOR TCP ON (CP.PROFESSOR_NO, TCP.PROFESSOR_NO)
--GROUP BY CLASS_NAME, PROFESSOR_NAME
--WHERE CP.PROFESSOR_
----WHERE DECODE(COUNT(CP.CLASS_NO) > 1, CP.PROFESSOR_NO != P.PROFESSOR_NO,  )
--ORDER BY PROFESSOR_NAME;


-- 9번 문제
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
RIGHT JOIN TB_CLASS_PROFESSOR CP USING (CLASS_NO)
LEFT JOIN TB_PROFESSOR P USING (PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';


-- 10번 문제 X--------------------------------------------------------
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT), 1)
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
GROUP BY STUDENT_NO, STUDENT_NAME;
WHERE DEPARTMENT_NAME = '음악학과';


-- 11번 문제
SELECT DEPARTMENT_NAME "학과이름", STUDENT_NAME "학생이름", PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';
-----------------------------------
SELECT DEPARTMENT_NAME "학과이름", STUDENT_NAME "학생이름", PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S
JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';




-- 12번 문제
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO LIKE '2007%'
AND CLASS_NAME = '인간관계론';


-- 13번 문제 X 담당교수 아직 못찾음
-- NULL 값 있는지 확인
SELECT CLASS_NAME, PROFESSOR_NO
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE PROFESSOR_NO IS NULL;

--MINUS
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM  TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;



-- 14번 문제
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;


-- 15번 문제
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름",
TRUNC(AVG(POINT), 8) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;


-- 16번 문제
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT), 8) "AVG(POING)"
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;


















